django6/advcbv/advcbv/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', views.index,name='index'),
    #url(r'^$', views.CBView.as_view()), class base
    url(r'^$', views.IndexView.as_view()), #template based
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app'))
]

django6/advcbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name='basic_app'

urlpatterns = [
url(r'^$',views.SchoolListView.as_view(),name='list'),
#r'^(?P<pk>[-\w]+)/$'
url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),


]

django6/advcbv/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail" , kwargs={'pk':self.pk})

class student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students')

    def __str__(self):
        return self.name

django6/advcbv/basic_app/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (View,TemplateView,ListView,DetailView,
                                    CreateView,UpdateView,DeleteView)
from . import models


class IndexView(TemplateView):
    template_name = 'index.html'
#from django.http import HttpResponse
# Create your views here.

 # simple view
# def index(request):
#     return render(request,'basic_app/index.html')

# class based view
# class CBView(View):
#     def get(self,request):
#         return HttpResponse("Class based views are cool !")

# templatebase view
# class IndexView(TemplateView):
#     template_name = 'basic_app/index.html'
#
#     def get_context_data(self,**kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme'] = 'BASCI INJECTION'
#         return context

  #ListView,DetailView
class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School
class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School
class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

django6/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link"  href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>

        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>

  </body>
</html>

django6/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block %}
<h1>Delete {{ school.name}}?</h1>
<form class="" method="post">
  {% csrf_token %}
  <input type="submit" name="delete" value="Delete" class="btn btn-danger">
  <a href="{% url 'basic_app:detail' pk=school.pk %}">cancel</a>
</form>

{% endblock %}

django6/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block %}
<div class="jumbotron">
  <h1>welcome to a school detail page </h1>

  <h2>school detail:</h2>
  <p>Name : {{ school_detail.name}}</p>
  <p>principal : {{ school_detail.principal}}</p>
  <p>location : {{ school_detail.location}}</p>

  <h3>students :</h3>
  {% for student in school_detail.students.all %}
  <p>{{ student.name }} who is {{ student.age }} year old.</p>
  {% endfor %}
</div>
<div class="container">
  <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">update</a></p>

</div>
{% endblock %}

django6/advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block %}
<h1>
{% if not form.instance.pk %}
create School
{% else %}
update School
{% endif %}
</h1>
<form  method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="submit" value="submit">
</form>
{% endblock %}

django6/advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block %}
<h1>welcome to a list of all the school</h1>
<ol>
  {% for school in schools %}

  <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
  {% endfor %}
</ol>
{% endblock %}

django6/advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link"  href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>
         
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>

  </body>
</html>

django6/advcbv/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link"  href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>
         
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>

  </body>
</html>

django6/advcbv/templates/basic_app/index.html

 {% extends "basic_app/base.html" %}
 {% block body_block %}
 <h1>testing template based view</h1>
 <h1>Injected content :{{ injectme}} </h1>
{% endblock %}

django6/advcbv/templates/index.html

 {% extends "basic_app/base.html" %}
 {% block body_block %}
 <h1>testing template based view</h1>
 <h1>Injected content :{{ injectme}} </h1>
{% endblock %}